DanPickford2.0/Models/danpage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DanPickford2._0.Models
{
    public class danpage
    {
        private string _backgroundImage;

        public string BackgroundImage
        {
            get { return _backgroundImage; }
            set { _backgroundImage = value; }
        }

    }
}

DanPickford2.0/Models/facebook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DotNetOpenAuth.OAuth.ChannelElements;
using DanPickford2._0.Classes;

namespace DanPickford2._0.Models
{
    public class facebook
    {

    }
}

DanPickford2.0/Models/smugmug.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DotNetOpenAuth.OAuth;
using DotNetOpenAuth.Messaging;
using DotNetOpenAuth.OAuth.ChannelElements;
using DanPickford2._0.Classes;
namespace DanPickford2._0.Models
{
    public class smugmug
    {

        public OAuthTokenManager InMemoryTokenManager = new OAuthTokenManager("ptImcZ4sIXVNENb5inyDpeBivcP6FEgB", "9ad05e770c6bce11a430fbfafae10396");

        public ServiceProviderDescription GetServiceDescription()
        {
            return new ServiceProviderDescription
            {
                AccessTokenEndpoint = new MessageReceivingEndpoint("https://api.smugmug.com/services/oauth/getAccessToken.mg", HttpDeliveryMethods.PostRequest),
                RequestTokenEndpoint = new MessageReceivingEndpoint("https://api.smugmug.com/services/oauth/getRequestToken.mg", HttpDeliveryMethods.PostRequest),
                UserAuthorizationEndpoint = new MessageReceivingEndpoint("https://api.smugmug.com/services/oauth/authorize.mg", HttpDeliveryMethods.PostRequest),
                TamperProtectionElements = new ITamperProtectionChannelBindingElement[] { new HmacSha1SigningBindingElement() },
                ProtocolVersion = ProtocolVersion.V10
            };
        }

    }
}

DanPickford2.0/Controllers/ChrisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DanPickford2._0.Controllers
{
    public class ChrisController : Controller
    {
        //
        // GET: /Chris/

        public ActionResult Index()
        {
            return View();
        }

    }
}

DanPickford2.0/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DanPickford2._0.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        // GET: /Home/About
        public ActionResult About()
        {

            return View();
        }

        // GET: /Home/DanDev
        public ActionResult DanDev()
        {

            return View();
        }

        // GET: /Home/Project
        public ActionResult Project()
        {

            return View();
        }
    }
}

DanPickford2.0/Controllers/MunchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DanPickford2._0.Controllers
{
    public class MunchController : Controller
    {
        //
        // GET: /Munch/

        public ActionResult Index()
        {
            return View();
        }
        //
        // GET: /Munch/GameStart

        public ActionResult GameStart()
        {
            return View();
        }

    }
}

DanPickford2.0/Controllers/OAuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DanPickford2._0.Models;
using DotNetOpenAuth.OAuth;
namespace DanPickford2._0.Controllers
{
    public class OAuthController : Controller
    {
        //
        // GET: /OAuth/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult StartOAuth()
        {
            smugmug myMug = new smugmug();

            var serviceProvider = myMug.GetServiceDescription();
            var consumer = new WebConsumer(serviceProvider, myMug.InMemoryTokenManager);

            // Url to redirect to
            var authUrl = new Uri(Request.Url.Scheme + "://" + Request.Url.Authority + "/OAuth/OAuthCallBack/");

            // request access
            
            consumer.Channel.Send(consumer.PrepareRequestUserAuthorization(authUrl, null, null));
            
            // This will not get hit!
            return null;
        }
        public ActionResult OAuthCallback()
        {
            smugmug myMug = new smugmug();
            // Process result from the service provider
            var serviceProvider = myMug.GetServiceDescription();
            var consumer = new WebConsumer(serviceProvider, myMug.InMemoryTokenManager);
            var accessTokenResponse = consumer.ProcessUserAuthorization(this.HttpContext.Request);
            var test = this.HttpContext.Request;
            // If we didn't have an access token response, this wasn't called by the service provider
            if (accessTokenResponse == null)
                return RedirectToAction("Index");

            // Extract the access token
            string accessToken = accessTokenResponse.AccessToken;

            ViewBag.Token = accessToken;
            ViewBag.Secret = myMug.InMemoryTokenManager.GetTokenSecret(accessToken);
            return View();
        }


    }
}

DanPickford2.0/Controllers/ParallaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DanPickford2._0.Controllers
{
    public class ParallaxController : Controller
    {
        //
        // GET: /Parallax/

        public ActionResult Index()
        {
            return View();
        }

    }
}

DanPickford2.0/Views/Chris/index.cshtml
@{
    ViewBag.Title = "Chris Equation Helper";
    Layout = null;
}
<script src="~/Content/JS/jquery-1.9.0.min.js"></script>
<link href="~/Content/Styles/Style1.css" rel="stylesheet" />
<div style="width: 70%; height: 98%; padding: 1% 15% 1% 15%; font-size: 16px;">
    <div style="padding: 1% 1% 1% 1%; height: 100%; background-image: url('../Content/Images/13959_198875141627_2120386_n.jpg'); background-repeat: no-repeat; background-size: cover;">
        <h2>Birthday Equation Helper</h2>
        <span>The equation: <br /> 
            A=((X-42)+(8.756583/X))<br />
            B=(A-40)+(22331/500000)</span>
        <br />
        <br />
        <input id="letterVal" type="hidden" value="empty" />
        <input id="Step" type="hidden" value="1" />
        <span id="step1">Enter the first letter of a country A for Africa,America,etc. and click next, letter: <input id="letter" type="text" style="width: 25px;" /><br /> Remember a and A have diferent ascii values.</span>
        <span id="step2" style="display: none; width: 40%;"></span>
        <span id="step3" style="display: none; width: 40%;"></span>
        <span id="step4" style="display: none; width: 40%;">So now we are working on what B is, the first part is A-40. Take the answer to the previous step and deduct 40 from it.</span>
        <span id="step5" style="display: none; width: 40%;">What is 22331 devided by 500000?</span>
        <span id="step6" style="display: none; width: 40%;">Add the last two answers together to get B. Congratulations you now have a longitude and latitude try googleing it!</span>
        <br /><br />
        <input id="stepChanger" type="button" value="Next" onclick="click_process();" />
        <span id="terms">By clicking next you acknowledge that Dan is a sexy beast.</span>
    </div>
</div>
<script type="text/javascript">
    function click_process(parameters) {
        var curStep = $('#Step').val();
        $('#step' + curStep).css('display', 'none');
        if ($('#letterVal').val() == 'empty') {
            $('#letterVal').val($('#letter').val().charCodeAt(0));
        }
        curStep = parseInt(curStep) + 1;
        $('#Step').val(curStep);
        //alert($('#Step').val());
        //alert(curStep);
        $('#step' + curStep).css('display', 'block');
        if (curStep == 2) {
            $('#terms').text('By clicking you acknowledge Dan is a legend.');
            $('#step' + curStep).text('The ASCII code for your letter is ' + $('#letterVal').val() + '. So the first step is X-42. Do ' + $('#letterVal').val() + '-42.');
        }
        if (curStep == 3) {
            $('#terms').text('By clicking you acknowledge Dan as your one true god.');
            $('#step' + curStep).text('The next part is 8.756583/X so divide 8.756583 by ' + $('#letterVal').val() + '. Now add the two answers together. This concludes A the 1st line of your equation oooh exciting onto B.');
        }
        if (curStep == 4) {
            $('#terms').text('By clicking you acknowledge bahh you get the idea.');
        }
        if (curStep == 5) {
            $('#terms').text('');
        }
        if (curStep == 6) {
            $('#terms').text('By clicking you reset this site.');
        }
        if (curStep == 7) {
            $('#Step').val(1);
            $('#letterVal').val('empty');
            $('#step1').css('display', 'block');
            $('#terms').text('');
        }
        //alert($('#letter').val().charCodeAt(0));
    }
</script>

DanPickford2.0/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<script src="~/Content/JS/Site/about.js"></script>
<script src="~/Content/JS/jquery-1.9.0.min.js"></script>
<script src="~/Content/JS/Quintus/quintus.js"></script>
<script src="~/Content/JS/Quintus/quintus_sprites.js"></script>
<script src="~/Content/JS/Quintus/quintus_scenes.js"></script>
<script src="~/Content/JS/Quintus/quintus_input.js"></script>
<script src="~/Content/JS/Quintus/quintus_2d.js"></script>
<script src="~/Content/JS/Quintus/quintus_touch.js"></script>
<script src="~/Content/JS/Quintus/quintus_ui.js"></script>
<script>
    var pageInt = 1;
    var menuItems = {"Up-to-date CV": "'http://www.danpickford.com/Content/CV/Daniel_Pickford_Curriculum_Vitae.docx'"};
</script>
<div id="LivesDiv" style="position: absolute; top: 20%; left: 35%; font-size: 16px; font-weight:bold; background-color: #fff; display: none; z-index: 50;">Lives:<span id="livesLeft">3</span></div>
<form id="CV" method="get" action="~/Content/CV/Daniel_Pickford_Curriculum_Vitae.docx">
    <canvas style="z-index: 2;" id='myName'></canvas>
</form>
<script src="~/Content/JS/AboutMeGame/Setup.js"></script>
<script src="~/Content/JS/AboutMeGame/Baddy.js"></script>
<script src="~/Content/JS/AboutMeGame/Goal.js"></script>
<script src="~/Content/JS/AboutMeGame/Player.js"></script>
<script src="~/Content/JS/AboutMeGame/Step.js"></script>
<script src="~/Content/JS/AboutMeGame/Spring.js"></script>
<script src="~/Content/JS/AboutMeGame/Level1.js"></script>
<script src="~/Content/JS/AboutMeGame/Level2.js"></script>
<script src="~/Content/JS/AboutMeGame/Level3.js"></script>
<script src="~/Content/JS/AboutMeGame/Engine.js"></script>
<script>
    $('#myName_container').css('position', 'absolute');
    $('#myName_container').css('top', '10%');
    $('#myName_container').css('left', '0');
    $('#myName_container').css('width', '100%');
    $('#myName_container').css('height', '80%');
    $('#myName_container').css('overflow', 'hidden');
    //$('#myName').css('width', '100%');
    //$('#myName').css('height', '100%');
    $("#myName").focus();
</script>

DanPickford2.0/Views/Home/DanDev.cshtml
@{
    ViewBag.Title = "Dan.Dev";
}
<script src="~/Content/JS/Site/danDev.js"></script>
<h2>Dan.Dev</h2>
<script>
    var pageInt = 3;
    var menuItems = {
        "my GitHub": "'https://github.com/danpickford'",
        "Parallax Project": "'@Url.Action("Index", "Parallax")'"
    };
</script>
<div style="position: absolute; top: 15%; left: 15%; width: 510px; opacity: 0.8; font-size: medium; padding: 10px;">
    <div style="background-color: #808080;">
        <p style="opacity: 1 !important">
            I've been working on my wedding site for months and it's finally published! Its working well all our guests are loving it, check it out at www.pookandbeans.co.uk. I've decided to make the repo private as I think I may be onto a winner here :)
        </p>
    </div>
    <div style="background-color: #778899;">
        <p style="opacity: 1 !important">Have a strong desire to head back to the Android development world - I never did publish that QR code generator, so handy for Xbox one codes "Xbox use code!".</p>
    </div>
    
</div>  

DanPickford2.0/Views/Home/Index.cshtml
@model DanPickford2._0.Models.danpage
@{
    ViewBag.Title = "DanPickford Home";
}
<script src="~/Content/JS/Site/index.js"></script>
<script>
    var pageInt = 0;
    var menuItems = {};
</script>

DanPickford2.0/Views/Home/Project.cshtml
@{
    ViewBag.Title = "Project";
}
<script src="~/Content/JS/Site/projects.js"></script>
<h2>Project</h2>
<script>
    var pageInt = 4;
    var menuItems = { "Munch Game": "'@Url.Action("Index", "Munch")'", "My smart wedding site" : "'http://www.pookandbeans.co.uk'" };
</script>

DanPickford2.0/Views/Munch/Index.cshtml
@{
    Layout = "muchLayout.cshtml";
    ViewBag.Title = "Munch Game";
}
<div id="munchBox" class="munchBox" onclick="clicker('@Url.Action("GameStart")')">
    <div style="height: 90%;">&nbsp;</div>
    <span style="font-weight: bold; color: #000; font-size: 18px;">The aim of the game is feed Munch. Luckily it's raining food just hit Click or swipe up to eat it. Munch will follow your mouse or finger.</span>
</div>

DanPickford2.0/Views/OAuth/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

DanPickford2.0/Views/OAuth/OAuthCallback.cshtml
@{
    ViewBag.Title = "OAuthCallback";
}

<h2>OAuthCallback Result</h2>
<h2>OAuth Secret: @ViewBag.Secret;</h2>
<h2>OAuth Token: @ViewBag.Token;</h2>

DanPickford2.0/Views/Parallax/index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;" />
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.3.0/build/cssreset/reset-min.css">
    <link href="~/Content/Styles/parallax.css" rel="stylesheet" />
    <title>Dan in Parallax</title>
    <script src="~/Content/JS/jquery-1.9.0.min.js"></script>
    <script src="~/Content/JS/Parallax/jquery.stellar.min.js"></script>
    <script src="~/Content/JS/Parallax/waypoints.min.js"></script>
    <script src="~/Content/JS/Parallax/jquery.easing.min.js"></script>
    <script src="~/Content/JS/Parallax/iscroll-lite.js"></script>
    <script src="~/Content/JS/Parallax/Parallax.js"></script>
</head>
<body>
    <div class="slide" id="slide1" data-slide="1" data-stellar-background-ratio="0.1 ">
        <span id="Written1" class="Written" data-stellar-ratio="0.1">This is a demonstration of <a class="linkDark" href="http://en.wikipedia.org/wiki/Parallax">Parallaxing</a>. I created this so that I could learn how it is done.</span>
        <span id="Written2" class="Written" data-stellar-ratio="0.1">How awesome is this!?!</span>
        <span id="Written3" class="Written" data-stellar-ratio="2">Look at this text it's moving faster than the rest! ... When you scroll.</span>
        <a class="button" data-slide="2" title=""></a>
    </div>
    <!--End Slide 1-->
    <div class="slide" id="slide2" data-slide="2" data-stellar-background-ratio="0.5">
        <div id="YOLOdiv">
            <!--Y-->
            <img style="position: absolute; top: 265px; left: 310px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="5.4" alt="">
            <img style="position: absolute; top: 265px; left: 330px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 280px; left: 318px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="7.4" alt="">
            <img style="position: absolute; top: 300px; left: 320px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="2.4" alt="">
            <img style="position: absolute; top: 315px; left: 315px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 340px; left: 320px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="4.35" alt="">
            <img style="position: absolute; top: 355px; left: 315px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="3.4" alt="">
            <img style="position: absolute; top: 380px; left: 320px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="3.6" alt="">
            <img style="position: absolute; top: 250px; left: 300px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="3.1" alt="">
            <img style="position: absolute; top: 250px; left: 340px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 230px; left: 350px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="4.4" alt="">
            <img style="position: absolute; top: 235px; left: 290px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="4.12" alt="">
            <img style="position: absolute; top: 220px; left: 360px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 215px; left: 275px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="4.4" alt="">
            <!--O-->
            <img style="position: absolute; top: 220px; left: 460px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="5.4" alt="">
            <img style="position: absolute; top: 232px; left: 490px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 245px; left: 510px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="7.4" alt="">
            <img style="position: absolute; top: 260px; left: 530px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="2.4" alt="">
            <img style="position: absolute; top: 275px; left: 528px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 299px; left: 530px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="4.35" alt="">
            <img style="position: absolute; top: 320px; left: 520px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="3.4" alt="">
            <img style="position: absolute; top: 340px; left: 510px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="3.6" alt="">
            <img style="position: absolute; top: 350px; left: 490px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="3.1" alt="">
            <img style="position: absolute; top: 365px; left: 460px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="3.1" alt="">
            <img style="position: absolute; top: 232px; left: 430px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 245px; left: 410px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="7.4" alt="">
            <img style="position: absolute; top: 260px; left: 395px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="2.4" alt="">
            <img style="position: absolute; top: 275px; left: 390px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 299px; left: 395px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="4.35" alt="">
            <img style="position: absolute; top: 320px; left: 405px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="3.4" alt="">
            <img style="position: absolute; top: 340px; left: 415px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="3.6" alt="">
            <img style="position: absolute; top: 350px; left: 426px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="3.1" alt="">
            <!--L-->
            <img style="position: absolute; top: 265px; left: 575px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 280px; left: 575px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="7.4" alt="">
            <img style="position: absolute; top: 300px; left: 575px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="2.4" alt="">
            <img style="position: absolute; top: 315px; left: 575px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 340px; left: 575px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="4.35" alt="">
            <img style="position: absolute; top: 355px; left: 575px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="3.4" alt="">
            <img style="position: absolute; top: 380px; left: 575px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="3.6" alt="">
            <img style="position: absolute; top: 250px; left: 575px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="3.1" alt="">
            <img style="position: absolute; top: 230px; left: 575px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="4.4" alt="">
            <img style="position: absolute; top: 380px; left: 595px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="5.4" alt="">
            <img style="position: absolute; top: 375px; left: 615px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="7.1" alt="">
            <img style="position: absolute; top: 378px; left: 638px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="10" alt="">
            <img style="position: absolute; top: 380px; left: 652px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="1.9" alt="">
            <!--O-->
            <img style="position: absolute; top: 220px; left: 760px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="4.4" alt="">
            <img style="position: absolute; top: 232px; left: 790px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 245px; left: 810px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="3.4" alt="">
            <img style="position: absolute; top: 260px; left: 830px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="2.4" alt="">
            <img style="position: absolute; top: 275px; left: 828px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 299px; left: 830px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="7.35" alt="">
            <img style="position: absolute; top: 320px; left: 820px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="3.4" alt="">
            <img style="position: absolute; top: 340px; left: 810px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="3.6" alt="">
            <img style="position: absolute; top: 350px; left: 790px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="6.1" alt="">
            <img style="position: absolute; top: 365px; left: 760px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="3.1" alt="">
            <img style="position: absolute; top: 232px; left: 730px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 245px; left: 710px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="3.4" alt="">
            <img style="position: absolute; top: 260px; left: 695px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="2.4" alt="">
            <img style="position: absolute; top: 275px; left: 690px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="6.4" alt="">
            <img style="position: absolute; top: 299px; left: 695px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="5.35" alt="">
            <img style="position: absolute; top: 320px; left: 705px;" src="~/Content/Images/Parallax/largeStar.png" data-stellar-ratio="3.4" alt="">
            <img style="position: absolute; top: 340px; left: 715px;" src="~/Content/Images/Parallax/smlStar.png" data-stellar-ratio="3.6" alt="">
            <img style="position: absolute; top: 350px; left: 726px;" src="~/Content/Images/Parallax/medStar.png" data-stellar-ratio="9.1" alt="">
        </div>

        <a class="button" data-slide="3" title=""></a>
    </div>
    <!--End Slide 2-->
    <div class="slide" id="slide3" data-slide="3" data-stellar-background-ratio="0.1">
        <div class="container">
            <img src="~/Content/Images/Munch/Munch.png" data-stellar-ratio="1.4" alt="">
            <img src="~/Content/Images/Munch/Doughnut.png" data-stellar-ratio="1.5"  alt="">
            <img src="~/Content/Images/Munch/Chicken_Leg.png" data-stellar-ratio="2.7" alt="">
            <img src="~/Content/Images/Munch/Munch_Eat.png" data-stellar-ratio="3"  alt="">
            <img src="~/Content/Images/Munch/Pizza.png" data-stellar-ratio="1"  alt="">
            <img src="~/Content/Images/Munch/Munch_Sad.png" data-stellar-ratio="1.5" alt="">
        </div>
        <span id="Written4" class="Written">Parallaxing is all over the place these days, adding <a class="linkDark" href="@Url.Action("Index", "Munch")">Munch</a> into the mix.</span>
        <a class="button" data-slide="4" title=""></a>
    </div>
    <!--End Slide 3-->
    <div class="slide" id="slide4" data-slide="4" data-stellar-background-ratio="1.5">
        <span style="color: #fff; font-size: 600%; position: absolute; top: 10%; left: 45%;">fin.</span>
        <div id="footer">
            <div id="footerWrapper">
                Developed using <a class="link" href="http://jquery.com/">JQuery</a>, <a class="link" href="http://markdalgleish.com/projects/stellar.js/">Stellar.js</a>, <a class="link" href="http://imakewebthings.com/jquery-waypoints/">Waypoints</a> and <a class="link" href="http://gsgd.co.uk/sandbox/jquery/easing/">Easing</a>
                <br />
                <a class="link" href="~/Home">danpickford.com</a>
            </div>
        </div>
    </div>
    <!--End Slide 4-->
</body>
</html>